<?php

$usertypes = parse_ini_file('../application/config/gatekeeper.ini.php', true);
$usertypes = $usertypes['roles'];

$data = null;

foreach($usertypes as $usertype=>$key):
	$data[] = array(
		'type' => 'h',
		'number' => '3',
		'elements' => array(
			array(
				'type' => 'link',
				'href' => '/#',
				'content' => 'poipi'
			)
		)
	);
endforeach;

$index_content = array(
	array(
		'type' => 'div',
		'id' => 'accordion',
		'elements' => array(
			array(
				'type' => 'h',
				'number' => '3',
				'elements' => array(
					array(
						'type' => 'link',
						'href' => '/#',
						'content' => 'poipi'
					)
				)
			),
			array(
				'type' => 'p',
				'content' => 'poipoipoipoi'
			),
			array(
				'type' => 'h',
				'number' => '3',
				'elements' => array(
					array(
						'type' => 'link',
						'href' => '/#',
						'content' => 'poipi'
					)
				)
			),
			array(
				'type' => 'p',
				'content' => 'poipoipoipoi'
			),
			array(
				'type' => 'h',
				'number' => '3',
				'elements' => array(
					array(
						'type' => 'link',
						'href' => '/#',
						'content' => 'poipi'
					)
				)
			),
			array(
				'type' => 'p',
				'content' => 'poipoipoipoi'
			),
			array(
				'type' => 'h',
				'number' => '3',
				'elements' => array(
					array(
						'type' => 'link',
						'href' => '/#',
						'content' => 'poipi'
					)
				)
			),
			array(
				'type' => 'p',
				'content' => 'poipoipoipoi'
			),
			array(
				'type' => 'h',
				'number' => '3',
				'elements' => array(
					array(
						'type' => 'link',
						'href' => '/#',
						'content' => 'poipi'
					)
				)
			),
			array(
				'type' => 'p',
				'content' => 'poipoipoipoi'
			),
			array(
				'type' => 'h',
				'number' => '3',
				'elements' => array(
					array(
						'type' => 'link',
						'href' => '/#',
						'content' => 'poipi'
					)
				)
			),
			array(
				'type' => 'p',
				'content' => 'poipoipoipoi'
			),
		)
	)
);

$registry = return_registry();
$index = new view($registry);
$index->displayContent($index_content);


//<div id="accordion">
//	<h3><a href="#">Section 1</a></h3>
//		<p>
//		Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer
//		ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit
//		amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut
//		odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.
//		</p>
//	<h3><a href="#">Section 2</a></h3>
//		<p>
//		Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet
//		purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor
//		velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In
//		suscipit faucibus urna.
//		</p>
//	<h3><a href="#">Section 3</a></h3>
//	<div>
//		<p>
//		Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.
//		Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero
//		ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis
//		lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.
//		</p>
//		<ul>
//			<li>List item one</li>
//			<li>List item two</li>
//			<li>List item three</li>
//		</ul>
//	</div>
//	<h3><a href="#">Section 4</a></h3>
//	<div>
//		<p>
//		Cras dictum. Pellentesque habitant morbi tristique senectus et netus
//		et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
//		faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
//		mauris vel est.
//		</p>
//		<p>
//		Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
//		Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
//		inceptos himenaeos.
//		</p>
//	</div>
//</div>
































//$usertypes = parse_ini_file('../application/config/gatekeeper.ini.php', true);
//$usertypes = $usertypes['roles'];
//
//$data = null;
//
//foreach($usertypes as $usertype=>$key):
//	$data[] = array(
//		'type' => 'div',
//		'elements' => array(
//			array(
//				'type' => 'link',
//				'href' => '/user/list/type/'.$usertype.'/',
//				'content' => ucfirst($usertype).' List'
//			)
//		)
//	);
//
//endforeach;
//
//$data[] = array(
//		'type' => 'link',
//		'href' => '/user/list/type/all/',
//		'content' => '&bull; List All'
//);
//
//$index_content = array(
//	array(
//		'type' => 'h',
//		'number' => '2',
//		'content' => 'Users'
//	),
//	array(
//		'type' => 'div',
//		'class' => 'accordion',
//		'elements' => $data
//	)
//);
//
//$registry = return_registry();
//$index = new view($registry);
//$index->displayContent($index_content);
?>

